FROM node

WORKDIR '/app/frontend'
COPY package.json .
#install dependencies
RUN npm install -g @angular/cli@7.1.2
RUN npm install
# install chrome for protractor tests
RUN mkdir /app/node_modules
RUN cp -r node_modules/font-awesome /app/node_modules/
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - > chromelog.txt
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' > chromelog.txt
RUN apt-get update && apt-get install -yq google-chrome-stable > chromelog.txt


COPY . .
CMD ng test --karmaConfig=./src/karma.prod.conf.js --watch=false
